# Generated by Django 5.0 on 2023-12-13 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='todo',
            name='timer_seconds',
            field=models.IntegerField(default=0, verbose_name='Час секундоміра'),
        ),
    ]
