# Generated by Django 5.0 on 2023-12-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0003_todo_deadline_todo_timer_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='timer_seconds',
        ),
    ]
