# Generated by Django 5.0 on 2023-12-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0005_todo_elapsed_time_todo_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='elapsed_time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='start_time',
        ),
    ]
