# Generated by Django 5.0 on 2023-12-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
    ]
