# Generated by Django 5.0 on 2023-12-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_task', '0002_alter_todoitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='elapsed_time',
            field=models.FloatField(default=0, verbose_name='Пройдений час'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час старту'),
        ),
    ]
