# Generated by Django 5.0 on 2023-12-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_task', '0003_todoitem_elapsed_time_todoitem_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='elapsed_time',
            new_name='elapsed_time_task',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='start_time',
            new_name='start_time_task',
        ),
    ]
